### ISSUE TITLE
Empty databases list

### ISSUE THREAD

**Issue by tlvince** [marten-de-vries/pouchdb-fauxton-firefox-addon#2]
I've a number of databases, but none are listed. 'Verify Installation' passes successfully.

![screen shot 2015-03-15 at 12 02 49](https://cloud.githubusercontent.com/assets/323761/6655906/931c8e14-cb0b-11e4-863a-5fb6ba64cfa9.png)

![screen shot 2015-03-15 at 12 03 03](https://cloud.githubusercontent.com/assets/323761/6655909/9e6bbd9e-cb0b-11e4-9e0b-b67ca585fbf6.png)

Firefox developer edition v38.0a2 (2015-03-15), PouchDB v3.2.1, pouchdb-inspector v0.1.1.

**Comment by marten-de-vries** [comment]
Can reproduce. Seems like firefox changed the location of idb files from storage/permanent to storage/default. Need to look up what the actual difference between the default/permanent/temporary directories is supposed to be, but as soon as that's done a fix should be pretty easy. :)

**Comment by tlvince** [comment]
:+1:

**Comment by marten-de-vries** [comment]
Working on this now.

**Comment by marten-de-vries** [comment]
Fixed: d7e26c719c2986ab91c81287f2ab593618782f27

**Comment by marten-de-vries** [comment]
I can't upload this fix yet to addons.mozilla.org due to https://bugzilla.mozilla.org/show_bug.cgi?id=1196230 yet. So for now download the xpi file as linked to in the README.md if you want to test.
